# Generated by Django 4.1.7 on 2024-12-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_learning", "0002_division"),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="select",
            field=models.BooleanField(default=False, help_text="select me"),
            preserve_default=False,
        ),
    ]
