# Generated by Django 4.1.7 on 2024-12-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_learning", "0003_division_select"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="priority",
            field=models.CharField(
                choices=[("H", "Hign"), ("M", "Medium"), ("L", "Low")],
                default="M",
                max_length=1,
                verbose_name="Learning Priorities",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=25, verbose_name="Employee Name"),
        ),
    ]
