# Generated by Django 4.1.7 on 2024-12-19 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_learning", "0004_employee_priority_alter_employee_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="reg_time",
            field=models.DateField(default=datetime.date.today, verbose_name="Date"),
        ),
    ]
